export const CAMPAIGN = {
  id: "goblin_caves",
  title: "Похід у Печери Гоблінів",
  acts: [
    {
      id: "act1",
      title: "Акт I — Крик із заїжджого двору",
      intro: "Зникає сестра шинкаря. Сліди ведуть у підземні лази під каплицею.",
      boss: "Гоблін-Збирник Мита",
      bossPower: 1500,
      quests: [
        { id: "a1_q1", type: "shop_purchase", target: 4, reward: { gold: 100, diamonds: 1 }, title: "Купіть 4 карти на ярмарку зброярів" },
        { id: "a1_q2", type: "duel_finished", target: 10, reward: { gold: 100, diamonds: 1 }, title: "Зіграйте 10 дуелей на міському плацу" },
        { id: "a1_q3", type: "card_upgraded", target: 3, reward: { gold: 100, diamonds: 1 }, title: "Удоскональте карти 3 рази у коваля" },
        { id: "a1_q5", type: "profile_saved", target: 1, reward: { gold: 30, diamonds: 1 }, title: "Збережіть профіль" },
        { id: "a1_q4", type: "reward_claimed", target: 3, reward: { gold: 50, diamonds: 1 }, title: "Отримайте 3 нагороди за завдання" },
      ],
    },
    {
      id: "act2",
      title: "Акт II — Мито печер і згаслі смолоскипи",
      intro: "Стежки ведуть глибше. Під каменем — мито, караул і перші тіні варти.",
      boss: "Капітан Підземної Варти",
      bossPower: 3000,
      quests: [
        { id: "a2_q1", type: "shop_purchase", target: 6, reward: { gold: 150, diamonds: 2 }, title: "Купіть 6 карт у контрабандистів" },
        { id: "a2_q2", type: "duel_finished", target: 12, reward: { gold: 150, diamonds: 2 }, title: "Зіграйте 12 дуелей у «Сірому турнірі»" },
        { id: "a2_q3", type: "card_upgraded", target: 4, reward: { gold: 150, diamonds: 2 }, title: "Удоскональте карти 4 рази (руни)" },
        { id: "a2_q4", type: "reward_claimed", target: 3, reward: { gold: 60, diamonds: 1 }, title: "Отримайте 3 нагороди за завдання" },
      ],
    },
    {
      id: "act3",
      title: "Акт III — Собор тіней і Чорний десятинник",
      intro: "Собор у пітьмі збирає десятину. Ім’я ворога вже відоме.",
      boss: "Чорний Десятинник",
      bossPower: 4500,
      quests: [
        { id: "a3_q1", type: "shop_purchase", target: 8, reward: { gold: 200, diamonds: 3 }, title: "Купіть 8 карт у монастирській лавці" },
        { id: "a3_q2", type: "duel_finished", target: 15, reward: { gold: 200, diamonds: 3 }, title: "Зіграйте 15 дуелей проти «випробувань»" },
        { id: "a3_q3", type: "card_upgraded", target: 5, reward: { gold: 200, diamonds: 3 }, title: "Удоскональте карти 5 разів (освячення)" },
        { id: "a3_q4", type: "shop_purchase", target: 1, reward: { gold: 80, diamonds: 1 }, title: "Купіть 1 «реліквію» в крамниці" },
      ],
    },
    {
      id: "act4",
      title: "Акт IV — Облога підземного трону",
      intro: "Коридори крові не прощають. Лишилась остання перековка перед штурмом.",
      boss: "Гоблін-Шаман (2 фази)",
      bossPower: 6000,
      quests: [
        { id: "a4_q1", type: "shop_purchase", target: 10, reward: { gold: 250, diamonds: 4 }, title: "Купіть 10 карт (інтендант дружини)" },
        { id: "a4_q2", type: "duel_finished", target: 18, reward: { gold: 250, diamonds: 4 }, title: "Зіграйте 18 дуелей у «Кривавих коридорах»" },
        { id: "a4_q3", type: "card_upgraded", target: 6, reward: { gold: 250, diamonds: 4 }, title: "Удоскональте карти 6 разів (легендарна перековка)" },
        { id: "a4_q4", type: "card_upgraded", target: 2, reward: { gold: 100, diamonds: 1 }, title: "Удоскональте 1 карту 2 рази (майстерний рівень)" },
      ],
    },
    {
      id: "act5",
      title: "Акт V — Король під плитами",
      intro: "Сестра — ключ до стародавньої брами. Час ламати трон.",
      boss: "Підземний Король (3 фази)",
      bossPower: 10000,
      quests: [
        { id: "a5_q1", type: "shop_purchase", target: 12, reward: { gold: 300, diamonds: 5 }, title: "Купіть 12 карт перед штурмом" },
        { id: "a5_q2", type: "duel_finished", target: 20, reward: { gold: 300, diamonds: 5 }, title: "Зіграйте 20 дуелей (елітна варта трону)" },
        { id: "a5_q3", type: "card_upgraded", target: 7, reward: { gold: 300, diamonds: 5 }, title: "Удоскональте карти 7 разів (королівський рівень)" },
      ],
    },
  ],
};
